# Generated by Django 5.2.17 on 2026-09-02 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("symbol", models.CharField(max_length=16, unique=True)),
                ("name", models.CharField(blank=True, max_length=160)),
                ("sector", models.CharField(blank=True, max_length=80)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="MarketRegime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("observed_at", models.DateTimeField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("BULLISH", "Bullish"),
                            ("NEUTRAL", "Neutral"),
                            ("HIGH_RISK", "High Risk"),
                        ],
                        max_length=16,
                    ),
                ),
                ("score", models.FloatField()),
                ("notes", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="PerformanceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("strategy", models.CharField(max_length=40)),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                ("trades", models.PositiveIntegerField(default=0)),
                ("win_rate", models.FloatField(default=0)),
                ("profit_factor", models.FloatField(default=0)),
                ("expectancy", models.FloatField(default=0)),
                ("max_drawdown", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="TradePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("trading_date", models.DateField(db_index=True)),
                ("strategy", models.CharField(default="momentum", max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAIT", "Wait"),
                            ("READY", "Ready"),
                            ("INVALIDATED", "Invalidated"),
                            ("CLOSED", "Closed"),
                        ],
                        default="WAIT",
                        max_length=16,
                    ),
                ),
                ("score", models.FloatField()),
                ("confidence", models.FloatField()),
                ("entry_low", models.DecimalField(decimal_places=2, max_digits=14)),
                ("entry_high", models.DecimalField(decimal_places=2, max_digits=14)),
                ("stop_loss", models.DecimalField(decimal_places=2, max_digits=14)),
                ("take_profit", models.DecimalField(decimal_places=2, max_digits=14)),
                ("risk_reward", models.FloatField()),
                ("position_size", models.PositiveIntegerField(default=0)),
                ("checks", models.JSONField(default=dict)),
                ("veto_reasons", models.JSONField(default=list)),
                ("commentary", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="trading.instrument"
                    ),
                ),
            ],
            options={
                "ordering": ["-trading_date", "-score"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("instrument", "trading_date", "strategy"),
                        name="unique_daily_strategy",
                    )
                ],
            },
        ),
    ]
