# Generated by Django 5.2.17 on 2026-09-02 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("COMPLETE", "Complete"),
                            ("FAILED", "Failed"),
                        ],
                        default="RUNNING",
                        max_length=12,
                    ),
                ),
                ("source", models.CharField(default="yahoo", max_length=32)),
                ("interval", models.CharField(default="1d", max_length=4)),
                ("instruments_scanned", models.PositiveIntegerField(default=0)),
                ("freshest_candle_at", models.DateTimeField(blank=True, null=True)),
                ("errors", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="Candle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "interval",
                    models.CharField(
                        choices=[("1d", "Daily"), ("5m", "Five minutes")],
                        default="1d",
                        max_length=4,
                    ),
                ),
                ("open", models.DecimalField(decimal_places=4, max_digits=16)),
                ("high", models.DecimalField(decimal_places=4, max_digits=16)),
                ("low", models.DecimalField(decimal_places=4, max_digits=16)),
                ("close", models.DecimalField(decimal_places=4, max_digits=16)),
                ("volume", models.BigIntegerField(default=0)),
                ("source", models.CharField(default="yahoo", max_length=32)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candles",
                        to="trading.instrument",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("instrument", "timestamp", "interval"), name="unique_candle"
                    )
                ],
            },
        ),
    ]
