# Generated by Django 5.2.17 on 2026-09-02 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0002_scanrun_candle"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("trained_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(default="hist_gradient_boosting", max_length=80)),
                ("status", models.CharField(default="TRAINED", max_length=16)),
                ("samples", models.PositiveIntegerField(default=0)),
                ("features", models.JSONField(default=list)),
                ("metrics", models.JSONField(default=dict)),
                ("artifact_path", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="LiveQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("price", models.DecimalField(decimal_places=4, max_digits=16)),
                ("change_percent", models.FloatField(default=0)),
                ("volume", models.BigIntegerField(default=0)),
                ("market_time", models.DateTimeField()),
                ("received_at", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(default="yahoo-stream", max_length=32)),
                (
                    "instrument",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_quote",
                        to="trading.instrument",
                    ),
                ),
            ],
        ),
    ]
