# Generated by Django 5.2.17 on 2026-09-02 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0003_modelrun_livequote"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("predicted_at", models.DateTimeField(auto_now_add=True)),
                ("signal_date", models.DateField(db_index=True)),
                ("horizon_days", models.PositiveSmallIntegerField(default=1)),
                ("model_name", models.CharField(max_length=80)),
                ("model_probability", models.FloatField()),
                ("quant_score", models.FloatField()),
                ("decision", models.CharField(max_length=16)),
                ("reference_price", models.DecimalField(decimal_places=4, max_digits=16)),
                ("predicted_direction", models.CharField(default="UP", max_length=8)),
                (
                    "realized_price",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
                ),
                ("realized_return", models.FloatField(blank=True, null=True)),
                ("was_correct", models.BooleanField(blank=True, null=True)),
                ("evaluated_at", models.DateTimeField(blank=True, null=True)),
                ("evidence", models.JSONField(default=dict)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="trading.instrument"
                    ),
                ),
                (
                    "trade_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trading.tradeplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-predicted_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("instrument", "signal_date", "model_name", "horizon_days"),
                        name="unique_prediction_record",
                    )
                ],
            },
        ),
    ]
