# Generated by Django 5.2.17 on 2026-09-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0004_predictionrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="performancesnapshot",
            name="equity_curve",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="performancesnapshot",
            name="parameters",
            field=models.JSONField(default=dict),
        ),
    ]
