# Generated by Django 5.2.17 on 2026-09-04 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_demoorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='audit_opinion',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='instrument',
            name='audit_risky',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instrument',
            name='has_recent_dilution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instrument',
            name='risk_flags_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BrokerFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_date', models.DateField(db_index=True)),
                ('cr1', models.FloatField(blank=True, help_text='Top-1 broker buy concentration (%)', null=True)),
                ('cr3', models.FloatField(blank=True, help_text='Top-3 broker buy concentration (%)', null=True)),
                ('cr5', models.FloatField(blank=True, help_text='Top-5 broker buy concentration (%)', null=True)),
                ('institutional_score', models.FloatField(default=50.0, help_text='0-100, higher = stronger bandar activity')),
                ('net_foreign_value', models.FloatField(blank=True, help_text='Net foreign buy value (Rp)', null=True)),
                ('top_brokers', models.JSONField(default=list, help_text='Top 10 brokers with buy/sell/net values')),
                ('raw_available', models.BooleanField(default=False)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_flows', to='trading.instrument')),
            ],
            options={
                'ordering': ['-trading_date'],
                'constraints': [models.UniqueConstraint(fields=('instrument', 'trading_date'), name='unique_broker_flow')],
            },
        ),
        migrations.CreateModel(
            name='ForeignFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_date', models.DateField(db_index=True)),
                ('net_foreign_buy', models.FloatField(default=0, help_text='Net foreign buy value in Rp (positive = buy)')),
                ('net_foreign_volume', models.BigIntegerField(default=0)),
                ('foreign_buy_value', models.FloatField(default=0)),
                ('foreign_sell_value', models.FloatField(default=0)),
                ('signal', models.CharField(choices=[('ACCUMULATE', 'Accumulate'), ('DISTRIBUTE', 'Distribute'), ('NEUTRAL', 'Neutral')], default='NEUTRAL', max_length=12)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_flows', to='trading.instrument')),
            ],
            options={
                'ordering': ['-trading_date'],
                'constraints': [models.UniqueConstraint(fields=('instrument', 'trading_date'), name='unique_foreign_flow')],
            },
        ),
        migrations.CreateModel(
            name='FundamentalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveSmallIntegerField(db_index=True)),
                ('period_quarter', models.PositiveSmallIntegerField(default=4)),
                ('per', models.FloatField(blank=True, help_text='Price-to-Earnings Ratio', null=True)),
                ('pbv', models.FloatField(blank=True, help_text='Price-to-Book Value', null=True)),
                ('roe', models.FloatField(blank=True, help_text='Return on Equity (%)', null=True)),
                ('der', models.FloatField(blank=True, help_text='Debt-to-Equity Ratio', null=True)),
                ('eps', models.FloatField(blank=True, help_text='Earnings Per Share', null=True)),
                ('revenue_growth', models.FloatField(blank=True, help_text='Revenue growth YoY (%)', null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundamentals', to='trading.instrument')),
            ],
            options={
                'ordering': ['-period_year', '-period_quarter'],
                'constraints': [models.UniqueConstraint(fields=('instrument', 'period_year', 'period_quarter'), name='unique_fundamental_period')],
            },
        ),
    ]
